name: Build and Check

on:
  push:
    branches: [ main ] # Adjust branches as needed
  pull_request:
    branches: [ main ] # Adjust branches as needed

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  check:
    strategy:
      matrix:
        node: [ 22, 23 ]
    runs-on: ubuntu-latest
    name: Zola Check for Node.js ${{ matrix.node }}
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: ${{ matrix.node }} # Use LTS

      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup pnpm
        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
        with:
          run_install: false # Disable auto-install

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install Zola
        run: |
          curl -sSL https://github.com/getzola/zola/releases/download/v0.22.1/zola-v0.22.1-x86_64-unknown-linux-gnu.tar.gz -o /tmp/zola.tar.gz
          tar -xzf /tmp/zola.tar.gz -C /tmp
          sudo install /tmp/zola /usr/local/bin/zola

      - name: Run Zola Check
        run: pnpm check

  build:
    strategy:
      matrix:
        node: [ 22, 23 ]
    runs-on: ubuntu-latest
    name: Zola Build for Node.js ${{ matrix.node }}
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: ${{ matrix.node }}

      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup pnpm
        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
        with:
          run_install: false # Disable auto-install

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install Zola
        run: |
          curl -sSL https://github.com/getzola/zola/releases/download/v0.22.1/zola-v0.22.1-x86_64-unknown-linux-gnu.tar.gz -o /tmp/zola.tar.gz
          tar -xzf /tmp/zola.tar.gz -C /tmp
          sudo install /tmp/zola /usr/local/bin/zola

      - name: Run Zola Build
        run: pnpm build
        env:
          GITHUB_TOKEN: ${{ secrets.GH_CARD_TOKEN || github.token }}
